# Generated by Django 2.2.7 on 2019-11-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='key',
            field=models.IntegerField(null=True),
        ),
    ]
